# Hardware configuration for elitedex
# This file should be generated by nixos-generate-config
# Replace this with your actual hardware configuration
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # Boot configuration - adjust for your system
  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "ehci_pci" "nvme" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/22b4dc6a-3db6-401c-9721-b2c7f721bec8";
      fsType = "btrfs";
      options = [ "subvol=@" ];
  };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/55CC-E173";
    fsType = "vfat";
  };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/889e5162-e925-47b6-b560-e188fabb02e6"; }
  ];

  # Enables DHCP on each ethernet and wireless interface
  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
