{ inputs, config, lib, pkgs, ... }:
{
  services.forgejo = {
    enable = true;
    stateDir = "/var/lib/forgejo";

    database.type = "sqlite3";
    lfs.enable = true;

    settings = {
      DEFAULT.APP_NAME = "Forgejo";
      server = {
        DOMAIN = "forgejo.fer.xyz";
        ROOT_URL = "https://forgejo.fer.xyz/";
        # Bind to netbird only; nginx-proxy-manager on butthead reverse-proxies
        # forgejo.fer.xyz over the netbird mesh.
        HTTP_ADDR = "0.0.0.0";
        HTTP_PORT = 3000;
        START_SSH_SERVER = true;
        SSH_DOMAIN = "forgejo.fer.xyz";
        SSH_LISTEN_HOST = "0.0.0.0";
        SSH_LISTEN_PORT = 222;
        SSH_PORT = 222;
        LANDING_PAGE = "explore";
      };
      service = {
        DISABLE_REGISTRATION = true;
        REQUIRE_SIGNIN_VIEW = false;
      };
      session.COOKIE_SECURE = true;
      repository.DEFAULT_BRANCH = "main";
      log.LEVEL = "Warn";
    };

    # SECRET_KEY, INTERNAL_TOKEN, JWT_SECRET, LFS_JWT_SECRET are
    # auto-generated by the forgejo module on first start and persisted
    # under /var/lib/forgejo. Switch to sops-managed secret files later
    # if you need cross-host migration / restore-from-backup of sessions.
  };

  # Expose only on the netbird mesh.
  networking.firewall.interfaces.wt0.allowedTCPPorts = [ 3000 222 ];
}
