#ENC[AES256_GCM,data:Z4pIkfHWkZ606+PCPradLXLQnhEIjcyjPQrT4BrG6TQQ70Smi+d+3u0RUJ/4WUujAaww3agPcwmqZxgqDeM=,iv:4JlFu7k1BtX4OuIObdzAoYbzXeiSCmk9vcOXiNpVNog=,tag:vVG86s2nR11cglHa2d5jVg==,type:comment]
#ENC[AES256_GCM,data:TqbW6bY+mx799a+2jOydlnpVu8Eyr6Qg9jesee437IarhsRF0g==,iv:2SQHhP6rWDTHFo5WNoCkxxXLuYalvsXy/mBuKbe43lI=,tag:MOmgYt2BmrnptoOGZy67aQ==,type:comment]
#ENC[AES256_GCM,data:pEdBxl39o3dtTqz7DJY9T9AYQrqcGJhGdBt4d/2JQIlnm2kksq5avzN3+UrJUqI=,iv:onSllQ1njlAJPgV6xgqSE0IioPz+4d0EyXPYYwUyJZQ=,tag:5tmwx+9YuLb1lKb3lJMrMA==,type:comment]
#ENC[AES256_GCM,data:tkEgU4yu2CPkBn+Dm1QrqXe7Vu3+t8DxhjeVAAZ5dohgDK5PMlux8UuegcZyXeYjir5DSjs/PCBhajPTC3q0cHQj4hBZRD+X5A==,iv:V86ZfvyLccErq27ZA43YbXF8+KubsFdkKj42U/KHAgI=,tag:6kUudt4d8fIiIzRGCsWpqg==,type:comment]
#ENC[AES256_GCM,data:Ldgt1GnAe6JqRfvgTLQ4t3u3V7b0EQpxcStfkf5UTxKzRY5kxNmYcCLmTD3LBnBjhYQ=,iv:rq2ioSao1ow/DAKro7hHuY8h3OWkQCjS2VF/dCqhZgw=,tag:MmQprOt+9F6g7MhssrHxTA==,type:comment]
domain: ENC[AES256_GCM,data:uz7CDxY4Jg==,iv:ZkNkg/En9tLITDsldq0au/7ZYDrEa6xqz86SKEGPe2U=,tag:rAFf2R1N6OZhyE+k/D+w5w==,type:str]
#ENC[AES256_GCM,data:oqe06RYNWKz4uawJXME1YlBU2CeUMANU11naEoPVqV83rVlFJt39y4wyYgs20t2YQN46Gx9ocfTD+0KMpBbc2437OcjwHwAONwKOX3X/Ew==,iv:O7fISUnn8uVnk5n9Py4BPTp9bY3ebKOz4b2CNEv/lzU=,tag:gJ3QQJ30/NPuw89Mba9v6w==,type:comment]
mesh_domain: ENC[AES256_GCM,data:k9n4YEoU17prfp7y+8kGohU=,iv:S5XS3iUD8z3uewcQF8C5Tk2uOaP9Uon2bkdEIGLQ79k=,tag:cWxYan1+dpJ4V9XB3c18VQ==,type:str]
#ENC[AES256_GCM,data:djVoYbI0ndYGVvkI3RNZy1AD51bQ2EJZSD8bLv21zSu7vqIOUn+U4L2FwJ7qzV10pLfqx7qwaDYp99bVrSLq1h6X2LRVFO9131I=,iv:rcCVJ3O4l8lcLE3KX8hWNucXkJhJPUPc4tDZqeh+lCw=,tag:Ta9c1b2pFI3OsGUmiz6K7A==,type:comment]
acme_email: ENC[AES256_GCM,data:5iubeCmnida5Q4segixGJbpo2Vo=,iv:nBQ/WWHOExifgTXnYhHkirw+3e/BwMHUTksAwNCyV5Y=,tag:tTcl54Xi0WU1c6b07LoIJA==,type:str]
#ENC[AES256_GCM,data:XVCzGuGBFRr40HPT9oIxRGXMdpjDxykv2hgpyeppk0Pp/RWbbX3Z00GhWfqSf00bBidyiCgGpb9i5uWwdtafHxSvi5mWSO2+fg==,iv:UU1UWLFgvLD5AFlK/vklYlAcql5ebwnnhr+wAe8B8D8=,tag:B47ApVl6ZmL2ukd0mfYubg==,type:comment]
#ENC[AES256_GCM,data:Oh+bklt4corHBfxd2SY+SmSvCG/eHz2ub5u1V4RbCAjs9wDRL5HtJcbxWUDoXUNSFnnZndNO/kslweuAXgTXjghn2f6bwDEf,iv:1KMMuMbfLa/4aITrU/EAVhnOJ9yllhrHbspeg6cx6YA=,tag:R44PymYv1476lblc0+AfQA==,type:comment]
subdomains:
    emby: ENC[AES256_GCM,data:p5G/71A=,iv:9/a+dR6RGFGueDRIGTufGrG+OzShZwbD6x2jBy7dBZw=,tag:kzTrufiEGoYEA/9++cMRSA==,type:str]
    lazylibrarian: ENC[AES256_GCM,data:uuy++g==,iv:b0Qm0zUsYnpJcdT4NCAt+uXbl6sDGffljYV9doaIi8Y=,tag:y/ShXzNUol0riK1Lz6UCOg==,type:str]
    home-assistant: ENC[AES256_GCM,data:Oi5OSg==,iv:FQjjQhcAR4e4D7qTa+uBnxq+LYnXfomuVyXjRM4vGd4=,tag:TWn9ZCilcZxeHMwqI+eyUA==,type:str]
    tar1090: ENC[AES256_GCM,data:lrPlXw31GVnx7w==,iv:OCp4Bq7ReE+4IZNasoJIEzqAh+wvBzpFK8kdszhVrPk=,tag:+lbLA8J5A2IVi9XODtu3fA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGx3V3J6QSBpNjdp
            UUlhazdFaFN2aFhnNmZCM3pkNmVISFNCWEtwekhBR2laNmlWNkM4CnN2NUhhU0M3
            N2lxNC9mbXRCbUZOVmRzNUg2MTRZUnZ3UVh0WlBWY3VvT0UKLS0tIENON1dob1pR
            U0xQdEEwT1Z2WjA1ZHNHL1JPb2F6cThUSTBDMHRBZkZ1SUkKXVx7f/IczLkJNuGm
            Gdh4prF89n+WazSsf7o6FzAUEQ8oUEzz4Eh2R+WzpUQN/qNWdSxQYNt/u+0ex1aD
            3KluoA==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIjL5IsHvPwtZhjj3VYpcKMoA68f7MlHvayhakVwdG+E
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHl0SzNOUSA0YVRV
            Qy96MHlpaEY2NU5TNGlNalJTUDROa1ZjN3NuVEJUcUxSRFlhSjJRCkdGSHVFMlA0
            Tzg3Q1VlbGlsckRtMXVlalVaR0lyL0JaK0hzb05rU0xpTlEKLS0tIHJ3OU5sbENO
            QVNNbE5nUjlvdzNHcWZJNjZzWjVRRExNK1dnOVoxR1pkTEEKuslUdIzaE0J4zjwV
            /ToyfPBvnVuiSmy1QbIeushSxmhycxRnAJLJZOcKooIKjXMEXScXz5i7JqXaSTuZ
            932aKA==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINQePaMUwEu3oPfVMg/Yk9BiX6QbDmxRBC3Icnd1GkGQ
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDEyaWNLdyByUG1j
            UTR0SjJIMENhbzN2U25vWFZpeXg0YURwU3VkRFZEeStNOFQ5UkFNClFwWHJFMFFt
            elhCSjZ4NG1ka0xTYnphYVl4OW5wU1c0QjhHY2FqZTJQL2cKLS0tIFliTXBONWFC
            Z1lZaE1ycTlOOEtjUlVXclJUYTBwV04zL3d6alNsL25JZE0KjKAy4JXgfEENVdte
            D7vZqFcRJRnjdODKS8YNPDRBA8SDHHPborxe6YqNVfXCqxoKXFwnGXNGETCbolkM
            /sbErQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBgTN8rJvs9tZlSA0t3lNQX4MY15aJWUjxASTz32NdHt
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IE93L3c4ZyBSRk43
            UlBSNVFnaXVmdVFuMmo4VldjSHYyWTJ2VklMZDNEVFhvS2xrOEhjCmVjZ2tjYjZQ
            eHRhZXBqNDhzb1k1ZUhpVUJIc0lzWFkvU0dFdXNGZk45L00KLS0tIE9tY0x4VGQz
            andXeGZUUE85SGtIU3NjYWJ4RDJ4eHdxam1VV0JnamxpZUEKkveafIACjDh7DW5y
            eLf0WWFjjMFKU1WiD92Wgr0okYzWlXLumMX4tZf5d2gL0qpP8QJ9mhQX4Iq+vQ59
            SA1Iaw==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDa46hBmT7aRcNtTSKRmzTG8VBBrf9dU+GsUMgMzS7ld
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHdpcWFqdyAvUERm
            VkpYSERQTG5oaDZzcjhudTFLTUlTd1ZxdVFzdVl1SEVkN0w2N3lBCnhyNkNVaVRs
            NjZyTU1nVVA3SzlrMEJhcVpDRzQ2WUVWZVVhMUJzM2VJNTQKLS0tIHJJSkJPeVk2
            TjJNT2NRV3ZBMDVTQVlLbGx0U2FqcDlkOHVGRUNVNHhKY0kKC333ekFsWv7HNHpx
            keTRZtUpnsHE0Uyqjk55q6rv2ChZPFSfpF6UB1xWh6xl5D1Dv/jPNBuJ2pJHJVic
            IL1DTA==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKjSXKkOBTwOny1O6ssb4yFOuntAKh07qiDjhJnVRXV2
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGMzYVN6QSA2ZGwx
            TW9rZ0xEVkp4YWRDU24yVXo4VDlCSzN1elVCeDkrclk3VkZtVHh3CkNjQ2k1SlNE
            ekRTTjR5ejMyYlUvZU5pcHJPQlhXWUh4bGliQ3RPVDZLdW8KLS0tIE04cnJEeU9V
            N0hqazRQRTFnK0dSVUdjaFpmL0JWRE80eDZ1MGxpUThZVjAKUsJkU7P3FQWXX3qN
            gJ8bxlSEgMEMC9ZUhsZ3UKaBRFBQ28zgrcc81JSiWf5lEn5cO+u7UsOOeVd20ekW
            X34OvQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICzC0DNxw+lrSBF/lgGMKY2eZJWm1KD1FP47sdakZP9Z
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IFJnNFM2QSA2QXdr
            L2N3SGtMcng2Zy9kTXBjNmdwMDVIUGpCTTdpRWRLZEZKd05mb1VNCkpBcExFamRY
            VkhuVEw0MmNUa3VGbmQzUENYVzVqQzFoQzZ2Tm9kZTFXbGsKLS0tIGttQ0JZb2NQ
            OFErcS9TNWFKUzZnNkxpdVBzS2NXaEtxWWFETUJwd2x5MGcKkv6DFTWe/GQDyqcP
            0J0epYEeCu0N3B6R7/n4ojeg3HEPHIwHIlNPlKT1nVLTcZ7OoopOzhLFEGYwMbPk
            1OKX+Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOt+r0UbKvmpLwz13qBbxlHyuL0BZ9sg2/L83Q4FA75S
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IE1iL2psQSA2MDZ2
            UktTdUtrV2JCdkpJQWFlREdjbTJGQ0E0TDM2Kytzei9uS1h4N1VZCkdpUmF5ajFQ
            Ti9LRzAyZWJjWU5WUit6K3RBRUJuK1I4bHUzaEwybEk1cDgKLS0tIGl3SzBIQzda
            RFl1alJDSVlzRkVkNHBSM3RCckdoc0F5L29JNGcvNUh5OXMKO6hh5oYZi251eYfe
            hBYWfL9SJQgYdeDFJf0rMcTXvDc8EBMscwwjwGuwjNhL8oxhX1r8LXHtiGmwJF21
            Vv93jg==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIN1eFJxVzMN3FeBbTas0G1lQgEnxk4oU9PJ5JM8xr5qu
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IEhKT0VnZyBOcWYr
            Y0pWT0ZCb0M5QXgyMDFNV3VZUXhUelN3a0ptTGhWYWJOS1VlWmp3CnBBVFdFS1po
            eFY2eHQ1NEozbit3REdpaHdnQzhUTGQyQndNd2lFQjdUY0kKLS0tIDdjZnBoaTdl
            QnZQanByUjlLVXJSWmNrYi9NRjY4ZmRYQXlZWUd5eFpIK1UK/f7/F2OXa4ROvCxo
            QrnLU32+D1YVeavRLwDS1H/CRKN+PMAqu2GPU5EOXASrB5/Xp7bhklu8QTkqXsQ9
            gnLn6A==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKPS9fMrBgKRc/ZsS0LjgjVs1UY7/OQ+1G/L5cEEytFq
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IFB5ZXp6ZyBuS2Vt
            QXRRTGt5VUFVNXkyMFd0V1hnRjc1ZEdaeWhCby92Nk1OcW8xNUI4ClQyZWpGQmJZ
            QWFRMEZLMGtycCtEVnFyUnlTUjQzb1QzZHZMbDU4UWUzdUUKLS0tIGpMSk9LTHFK
            SURrOUNKckNwLzZLbWtGMGQyTEVOYS9FU0o2c1dweC91YzQKrksdFxjEFT4PHjDw
            F8CLOBlNrMBz3P/PIjfjDuoKyzcunYOopCYLHQeyutVwHGrGNHoXKrOy6/Qf5k7x
            s5Hj6Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICQ5a7p+8LrnKTch/UUAJ3YpAYT6PS8fM+0FKtSspZ5U fjimenez@vfjimenez
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4WWVDVUNUSkJaYmM5dUVU
            QURRbWZUdTUwNXRST0p6MEhsVUxWK05PTUFvClB5eDg1Y0JtSll4VjRYSUFLM1hL
            QmlNZmE3SFBReHBNcXVMSlNqV1pJeGcKLS0tIEt3dHhMVVpxbGllZ01QVnA1ZlBt
            UHJiRGdVN0NiYU1hTkpYdDlEVW5ndFEK1GA3/hYiUaURcQjFl9tNJ9fqKewJrIkt
            VibNFPeDGKaRNT5ilpMVqJd3rJOVFiUvBZzqRHl+SsDHFys/xOWNuw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pluz63z5cwmen53a58ng4tvjh6yrh8d3xvgvyjkvx7rcltug5anqw0fyyn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwSzZhcDRxeFhUazR6eDRp
            b05JWmFrbC9heGRWZTlrQ0xXbGhYcy9QVjBNCjNmakljSmdGcEJHcTZNQkZlUzF4
            U1p4UHRqb0FSVmp5TmQ1aldIb0MyZncKLS0tIDFlZXdEd1RjWS9SQ003VGRVK2wy
            Zm9nekhrSFh0eEJtUnRFUnp0N1crQzAKy3Yu6QlqM6yklBKpmEcU0EwEQBjbpzjL
            Wb/VEfjkprWfJKcTXP9XkBVtTlULboIQ4YSmk+ve38kScKD7tFZnaw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hva90d7n8xdqhus9r9r96pfs6uyrglkh7446l7hde40j4kg9pugstjczuv
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRMFRzeGhtaS9hMDVZMVZV
            MHAxL0tmYURBMHBpN3dQOUJWSGJFdzg2UkJrCmxoNTdSZHlXQmMzQ2pMM3k2SWEz
            OE1oVkM2NU5GdHRxRWNCUWtzcnY3OUUKLS0tIEg3UjB3RXlvMzkyc3gwNDdmOGJB
            TXdnREROZkNwSUpsR2ZKQXA4VDkzTEEKNPs2/CsRK5gK/6LV2Nh1mQwQ+Lvo3Jjs
            KVxiR2r1Fh3tUZLUAQmg4N1QvMT3SusUWvqEYhPI6teF5MhQ5VVCjQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m5q2w5ezcrys2zj5mq20wcc37f5qurpeuc0g33e7969rzzxajsyq5apfqj
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYMkFWdmszcTZaR3RIbnVn
            M3NVN0RGVFJabXVFVUVwWjZIZGUxRmtILzJBCmpWeVhqMk5RdzliTDBRemtTQUM2
            TERmOGh6S1p4Mm5wcWhNcmdTMWFtSU0KLS0tIDU3QmNJSG0yK0ZDQVBFdG93d1ZR
            WXl2OUVJcm0vQi82YVNkSHhaMFJSWjgKjOGmw1QxTPTZcYgtzsejvv4jmCGfZwk4
            S3xSYPpkk6b4zl+Rm38LzegdNFH+BJdDi81DGHC7XB0p+m7XkbDCJA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tm9cm7cvu76dgdgrg88ws2y2zfjyzmr2rpwrl3fjczpzc3zsmyvsgkne0c
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYb0Q4WUUvOG9TbkV2YlEr
            b3ZVRTNmWW5NZzdFVnF2NWtYeGJCNWRlVGxJCnZCZ042WGJyZWp4UktaaFA3cThP
            WnRPbmF1VWVoZWhsa1NsQkdXdWdPbGMKLS0tIGZlbW5aR2h4NlRyYnhSS3dVL2hr
            SzN5cUhCUUJiaGtQN1B6TE5IQ25ObjQK3bu2Vy+cgUHLWi4/a7RhfqN7tuARhMqj
            StcaKi8BvM7B+IS3Bk7u1zLF0ekQsrusO6jWfDLHp/9Atxgbv0vRqg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18hutz4xq0lk2y0vy0flk5w0qx5as8xlr9k0wd5qshjvglldceq6spxmp02
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4aU5YcGNVdVE2c2M4N2pn
            anQzbGJlWHZFMG0zWG5IeFNIZm5idXZJRXhvCnQxNXJsVTArd1lHSloxaTRiVmRZ
            RGZ2ZW1icnBLSmpVc01rd2RGNURyUG8KLS0tIHdBbVpWSEgzUTFrZHhrZFk0aTgr
            eUpXZ0VkQjg3aFB5YmdDY3VzWnhJdjAKr0zeUoyD67JkhecWn5KaXVeizeSi0MYQ
            hc6gkqfQhfsMCArdX13Fu/iLh7bAtVzLUsQF1ZgCIFxXMAEPbuHx8Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1za9qg39ygxc4xlda6elmmk3fq2845j3r2dv6qw3fvkjdtcklhvqsqfvvxv
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOazJLbzdQRXI2dldNazJF
            cWR1RTQ1QVFIaG1kMWtNamRuYkdwMVZWbzJvCnBVNU9MUWkvQno4eHFQRDRWdGJ4
            cWU2YW5Yd1dycjdaMVVxOEljYWdsdkkKLS0tIE91WmhadTJqK1ZzK2RObE8ra25a
            d2g5aVNYbUhnc0dBWSthWXJBTVE3VVUK66V9ji/AeHwWF1SiXwvjs/njRtuhlhxJ
            /Nx/aBhWwLKcwAnfYMMFVjp9uBTgAocpcKFG2enaSdJ8LPnEWxeXqQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1t60rm2grrq3zrhpgpgxz4uc3un7wuy93j3nvp6j7uujkn5l52qasclxhdl
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2akJMbE9WNEt1bFJFUkJ3
            Rnp4TmtPNHBTUmNXa2tXZkVSTW5xNFFRaTJNCktPTEFaZDhWVGdPSlhKdFhINm1H
            Ly9FKzdKMzZxTzRqMzZLVXEyUXk0dDQKLS0tIGpWS1ZmV0UwNEEzUFBYWTMwUjZH
            TnpVc3FCN1ZrZ0t2VGsrVmk5ZkJlMWcKlnrL0QyAwNHSGWi/i/MELFT4m0qX2O7N
            wK2WZLIvK9p0TABFQcWwlE4xV7VaX9eM+MwGk9cIp/4RL4mG1fhT+A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v4sun8t2ggdyv97kvgcep3mh2fjja95509x7sufkx487jp5egvks7sy8k4
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5eTlMaWVudnBHVGtTL1ZM
            aG1RUVJXUjhYZEhzZWo5Q0dzNFg1MGlhV0V3CktxVXFvTS8vZ09jYjYxY29ENW9o
            M1dCVmJiTTVYT0l4VGRVRTEveW5JMm8KLS0tIHBObHBXMDlEWk1UZ0RDWHgvSEhO
            OXQ0czg1ODAxaFdZcWk2cTdBKzZBdjAK+WTaZRlR82IUEdrHIC6G00DvzRUofE7Y
            NXKvZKGLQA0DBK3EOZSRfGNzXm7Sftq0JidDh579xPumxe6vb7rECg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vsjplswaaj0dja82u939ng9h9wftm6rdjqlzgjsjykg55j7q83csx72nq6
    lastmodified: "2026-09-28T21:51:52Z"
    mac: ENC[AES256_GCM,data:lCDhWhB1jxlSV6xbKG03k9F1ADIy6mIJ7FQiKZ0JFurLvaOsj0x1mLFL0Wg8Rsi93vrZxVKNZqnD/x9cy4FVKXRS9pqrOgAEJxAVS5oz1QesKADoL8CO/RQtlayUK+7ccV+Oi62KVOQL5/QtLIRuo+W38DThYbVfakJrVuBeUmQ=,iv:0ZlxF+imQ2NdBXfw2Ka6/hXm8JxKEZZCdBd55bQde9g=,tag:GDLl91OKOFxc1DQZswMM4A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
